// Copyright (C) 2026 Glauco Pacheco <glaucopacheco@gmail.com>
// SPDX-License-Identifier: AGPL-3.0-only OR MPL-2.0-no-copyleft-exception

#ifndef SPECTATOR_MACRO_HELPERS_H
#define SPECTATOR_MACRO_HELPERS_H

#define _SPECTATOR_CONCATENATE_IMPL_(a, b) a ## b
#define _SPECTATOR_CONCATENATE_(a, b) _SPECTATOR_CONCATENATE_IMPL_(a, b)
#define _SPECTATOR_TO_UTF_16_STRING_LITERAL_IMPL(str) u##str
#define _SPECTATOR_TO_UTF_16_STRING_LITERAL(str) _SPECTATOR_TO_UTF_16_STRING_LITERAL_IMPL(str)
#define _SPECTATOR_MAKE_UTF_16_STRING_IMPL(...) _SPECTATOR_TO_UTF_16_STRING_LITERAL(#__VA_ARGS__)
#define _SPECTATOR_MAKE_UTF_16_STRING(...) _SPECTATOR_MAKE_UTF_16_STRING_IMPL(__VA_ARGS__)

#endif // SPECTATOR_MACRO_HELPERS_H
